-- ============================================
-- Growny-AI Supabase Schema
-- Run this ENTIRE file in Supabase SQL Editor
-- ============================================

-- STEP 1: Enable pgvector extension (required for embeddings)
CREATE EXTENSION IF NOT EXISTS vector;

-- STEP 2: Drop old functions to avoid conflicts
DROP FUNCTION IF EXISTS match_tasks(vector, double precision, integer);
DROP FUNCTION IF EXISTS match_tasks(vector, float, int);
DROP FUNCTION IF EXISTS match_tasks(vector, float, int, text);

-- STEP 3: Create tasks table (if not exists)
CREATE TABLE IF NOT EXISTS tasks (
  id bigint generated by default as identity primary key,
  user_id text not null,
  content text not null,
  raw_text text,
  category text,
  priority text,
  due_date text,
  embedding vector(768) DEFAULT NULL,
  created_at timestamptz default now()
);

-- STEP 4: FIX - Make embedding column nullable (THIS FIXES THE VECTOR ERROR!)
ALTER TABLE tasks ALTER COLUMN embedding DROP NOT NULL;

-- STEP 5: Create index for faster user queries
CREATE INDEX IF NOT EXISTS tasks_user_id_idx ON tasks(user_id);

-- STEP 6: Create vector search function
CREATE OR REPLACE FUNCTION match_tasks (
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  filter_user_id text
)
RETURNS TABLE (id bigint, content text, category text, priority text, due_date text, similarity float)
LANGUAGE sql STABLE AS $$
  SELECT 
    id, content, category, priority, due_date,
    1 - (embedding <=> query_embedding) AS similarity
  FROM tasks
  WHERE user_id = filter_user_id
    AND embedding IS NOT NULL
    AND 1 - (embedding <=> query_embedding) > match_threshold
  ORDER BY embedding <=> query_embedding 
  LIMIT match_count;
$$;

-- STEP 7: Enable Row Level Security
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- STEP 8: Drop and recreate policies
DROP POLICY IF EXISTS "Users can view own tasks" ON tasks;
DROP POLICY IF EXISTS "Users can insert own tasks" ON tasks;
DROP POLICY IF EXISTS "Users can update own tasks" ON tasks;
DROP POLICY IF EXISTS "Users can delete own tasks" ON tasks;

CREATE POLICY "Users can view own tasks" ON tasks FOR SELECT USING (true);
CREATE POLICY "Users can insert own tasks" ON tasks FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update own tasks" ON tasks FOR UPDATE USING (true);
CREATE POLICY "Users can delete own tasks" ON tasks FOR DELETE USING (true);

-- STEP 9: Verify the fix worked
SELECT 
  column_name, 
  is_nullable
FROM information_schema.columns
WHERE table_name = 'tasks' AND column_name = 'embedding';
-- Should show: is_nullable = YES
