-- ============================================
-- Growny-AI Supabase Schema
-- Run this ENTIRE file in Supabase SQL Editor
-- ============================================

-- STEP 1: Enable pgvector extension (required for embeddings)
CREATE EXTENSION IF NOT EXISTS vector;

-- STEP 2: Drop old functions to avoid conflicts
DROP FUNCTION IF EXISTS match_tasks(vector, double precision, integer);
DROP FUNCTION IF EXISTS match_tasks(vector, float, int);
DROP FUNCTION IF EXISTS match_tasks(vector, float, int, text);

-- STEP 3: Create tasks table (if not exists)
CREATE TABLE IF NOT EXISTS tasks (
  id bigint generated by default as identity primary key,
  user_id text not null,
  content text not null,
  raw_text text,
  category text,
  priority text,
  due_date text,
  embedding vector(768) DEFAULT NULL,
  created_at timestamptz default now()
);

-- STEP 4: FIX - Make embedding column nullable (THIS FIXES THE VECTOR ERROR!)
ALTER TABLE tasks ALTER COLUMN embedding DROP NOT NULL;

-- STEP 5: Create index for faster user queries
CREATE INDEX IF NOT EXISTS tasks_user_id_idx ON tasks(user_id);

-- STEP 6: Create vector search function
CREATE OR REPLACE FUNCTION match_tasks (
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  filter_user_id text
)
RETURNS TABLE (id bigint, content text, category text, priority text, due_date text, similarity float)
LANGUAGE sql STABLE AS $$
  SELECT 
    id, content, category, priority, due_date,
    1 - (embedding <=> query_embedding) AS similarity
  FROM tasks
  WHERE user_id = filter_user_id
    AND embedding IS NOT NULL
    AND 1 - (embedding <=> query_embedding) > match_threshold
  ORDER BY embedding <=> query_embedding 
  LIMIT match_count;
$$;

-- STEP 7: Enable Row Level Security
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- STEP 8: Drop and recreate policies
DROP POLICY IF EXISTS "Users can view own tasks" ON tasks;
DROP POLICY IF EXISTS "Users can insert own tasks" ON tasks;
DROP POLICY IF EXISTS "Users can update own tasks" ON tasks;
DROP POLICY IF EXISTS "Users can delete own tasks" ON tasks;

CREATE POLICY "Users can view own tasks" ON tasks FOR SELECT USING (true);
CREATE POLICY "Users can insert own tasks" ON tasks FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update own tasks" ON tasks FOR UPDATE USING (true);
CREATE POLICY "Users can delete own tasks" ON tasks FOR DELETE USING (true);

-- ============================================
-- STEP 9: Transactions table (Money Pillar)
-- ============================================
CREATE TABLE IF NOT EXISTS transactions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  type text not null check (type in ('INCOME', 'EXPENSE')),
  amount decimal(12,2) not null,
  currency text default 'INR',
  category text,
  description text not null,
  source text default 'chat',
  date date default current_date,
  tags text[] default '{}',
  raw_text text,
  created_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS transactions_user_id_idx ON transactions(user_id);
CREATE INDEX IF NOT EXISTS transactions_date_idx ON transactions(date);
CREATE INDEX IF NOT EXISTS transactions_type_idx ON transactions(type);

ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own transactions" ON transactions;
DROP POLICY IF EXISTS "Users can insert own transactions" ON transactions;
DROP POLICY IF EXISTS "Users can update own transactions" ON transactions;
DROP POLICY IF EXISTS "Users can delete own transactions" ON transactions;

CREATE POLICY "Users can view own transactions" ON transactions FOR SELECT USING (true);
CREATE POLICY "Users can insert own transactions" ON transactions FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update own transactions" ON transactions FOR UPDATE USING (true);
CREATE POLICY "Users can delete own transactions" ON transactions FOR DELETE USING (true);

-- ============================================
-- STEP 10: Documents table (Knowledge Base)
-- ============================================
CREATE TABLE IF NOT EXISTS documents (
  id bigint generated by default as identity primary key,
  user_id text not null,
  filename text not null,
  file_type text,
  file_size bigint,
  content_text text,
  metadata jsonb default '{}',
  uploaded_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS documents_user_id_idx ON documents(user_id);

ALTER TABLE documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own documents" ON documents;
DROP POLICY IF EXISTS "Users can insert own documents" ON documents;
DROP POLICY IF EXISTS "Users can delete own documents" ON documents;

CREATE POLICY "Users can view own documents" ON documents FOR SELECT USING (true);
CREATE POLICY "Users can insert own documents" ON documents FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can delete own documents" ON documents FOR DELETE USING (true);

-- ============================================
-- STEP 11: Document chunks for RAG search
-- ============================================
CREATE TABLE IF NOT EXISTS document_chunks (
  id bigint generated by default as identity primary key,
  document_id bigint references documents(id) on delete cascade,
  user_id text not null,
  chunk_index int,
  content text not null,
  embedding vector(768),
  created_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS doc_chunks_user_id_idx ON document_chunks(user_id);
CREATE INDEX IF NOT EXISTS doc_chunks_document_id_idx ON document_chunks(document_id);

ALTER TABLE document_chunks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own chunks" ON document_chunks;
DROP POLICY IF EXISTS "Users can insert own chunks" ON document_chunks;
DROP POLICY IF EXISTS "Users can delete own chunks" ON document_chunks;

CREATE POLICY "Users can view own chunks" ON document_chunks FOR SELECT USING (true);
CREATE POLICY "Users can insert own chunks" ON document_chunks FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can delete own chunks" ON document_chunks FOR DELETE USING (true);

-- STEP 12: RAG search function for document chunks
CREATE OR REPLACE FUNCTION match_document_chunks (
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  filter_user_id text
)
RETURNS TABLE (id bigint, document_id bigint, chunk_index int, content text, similarity float)
LANGUAGE sql STABLE AS $$
  SELECT
    id, document_id, chunk_index, content,
    1 - (embedding <=> query_embedding) AS similarity
  FROM document_chunks
  WHERE user_id = filter_user_id
    AND embedding IS NOT NULL
    AND 1 - (embedding <=> query_embedding) > match_threshold
  ORDER BY embedding <=> query_embedding
  LIMIT match_count;
$$;

-- ============================================
-- CRITICAL FIX: Firebase Auth Integration
-- Since we use Firebase for authentication, Supabase RLS (which expects Supabase Auth)
-- will block our backend requests. Since our FastAPI backend securely verifies the 
-- Firebase token before making any database queries, we must disable RLS on these tables.
-- ============================================
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE document_chunks DISABLE ROW LEVEL SECURITY;