-- Growny-AI Supabase Schema with Multi-User Support
-- Run this in your Supabase SQL Editor

-- 1. DROP old functions
DROP FUNCTION IF EXISTS match_tasks(vector, double precision, integer);
DROP FUNCTION IF EXISTS match_tasks(vector, float, int);
DROP FUNCTION IF EXISTS match_tasks(vector, float, int, text);

-- 2. Add created_at column if it doesn't exist (run this separately if table exists)
-- ALTER TABLE tasks ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

-- 3. CREATE TABLE with user_id for multi-user support
CREATE TABLE IF NOT EXISTS tasks (
  id bigint generated by default as identity primary key,
  user_id text not null,
  content text not null,
  raw_text text,
  category text,
  priority text,
  due_date text,
  embedding vector(768),
  created_at timestamptz default now()
);

-- 4. CREATE INDEX
CREATE INDEX IF NOT EXISTS tasks_user_id_idx ON tasks(user_id);

-- 5. CREATE SEARCH FUNCTION
CREATE OR REPLACE FUNCTION match_tasks (
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  filter_user_id text
)
RETURNS TABLE (id bigint, content text, category text, priority text, due_date text, similarity float)
LANGUAGE sql STABLE AS $$
  SELECT 
    id, content, category, priority, due_date,
    1 - (embedding <=> query_embedding) AS similarity
  FROM tasks
  WHERE user_id = filter_user_id
    AND 1 - (embedding <=> query_embedding) > match_threshold
  ORDER BY embedding <=> query_embedding 
  LIMIT match_count;
$$;

-- 6. Enable RLS
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- 7. DROP existing policies
DROP POLICY IF EXISTS "Users can view own tasks" ON tasks;
DROP POLICY IF EXISTS "Users can insert own tasks" ON tasks;
DROP POLICY IF EXISTS "Users can update own tasks" ON tasks;
DROP POLICY IF EXISTS "Users can delete own tasks" ON tasks;

-- 8. CREATE policies
CREATE POLICY "Users can view own tasks" ON tasks FOR SELECT USING (true);
CREATE POLICY "Users can insert own tasks" ON tasks FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update own tasks" ON tasks FOR UPDATE USING (true);
CREATE POLICY "Users can delete own tasks" ON tasks FOR DELETE USING (true);

-- 9. If table exists without created_at, run this:
-- ALTER TABLE tasks ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
